version: "3.5"

services:
  zkevm-mock-l1-network:
    container_name: zkevm-mock-l1-network
    image: hermeznetwork/geth-zkevm-contracts:v1.1.0-snapchain
    ports:
      - 18545:8545
      - 18546:8546
    environment:
      - VIRTUAL_HOST=rpc-l1.<user-rollup-identifier>
      - LETSENCRYPT_HOST=rpc-l1.<user-rollup-identifier>
      - VIRTUAL_PORT=8545
      - L2_CHAIN_ID=2955
    entrypoint:
      - /usr/local/bin/geth
      - "--http"
      - "--http.api"
      - "admin,eth,debug,miner,net,txpool,personal,web3"
      - "--http.addr"
      - "0.0.0.0"
      - "--http.corsdomain"
      - "*"
      - "--http.vhosts"
      - "*"
      - "--ws"
      - "--ws.origins"
      - "*"
      - "--ws.addr"
      - "0.0.0.0"
      - "--dev"
      - "--datadir"
      - "/geth_data"
      - "--syncmode"
      - "full"
      - "--rpc.allow-unprotected-txs"