version: "3.3"
services:
  zkevm-mock-l1-network:
    container_name: zkevm-mock-l1-network
    image: snapchain/geth-cdk-validium-contracts:v0.0.3
    ports:
      - 8545:8545
      - 8546:8546
    volumes:
      - deploy-output:/deploymentOutput
      - zkevm_mock_l1_geth_data:/geth_data
    command:
      - "--http"
      - "--http.api"
      - "admin,eth,debug,miner,net,txpool,personal,web3"
      - "--http.addr"
      - "0.0.0.0"
      - "--http.corsdomain"
      - "*"
      - "--http.vhosts"
      - "*"
      - "--ws"
      - "--ws.origins"
      - "*"
      - "--ws.addr"
      - "0.0.0.0"
      - "--dev"
      - "--dev.period"
      - "1"
      - "--datadir"
      - "/geth_data"
      - "--rpc.allow-unprotected-txs"

volumes:
  deploy-output:
  zkevm_mock_l1_geth_data: